// FILE: services/pettyCashService.ts
import { supabase } from './supabaseClient';

export interface PettyCashEntry {
  id: string;
  tgl: string;
  keterangan: string;
  type: 'in' | 'out';
  akun: 'cash' | 'bank'; // Kas atau Rekening
  saldokeluarmasuk: number; // Jumlah transaksi (positif)
  saldosaatini: number; // Saldo setelah transaksi
}

// Helper: Get table name based on store
const getTableName = (store: string | null): string => {
  return store === 'bjw' ? 'petty_cash_bjw' : 'petty_cash_mjm';
};

// Helper: Parse angka dari input dengan format Indonesia (titik sebagai pemisah ribuan)
export const parseIndonesianNumber = (value: string): number => {
  if (!value) return 0;
  const cleaned = value
    .replace(/[^\d.,]/g, '')
    .replace(/\./g, '')
    .replace(/,/g, '.');
  
  const result = parseFloat(cleaned);
  return isNaN(result) ? 0 : result;
};

// Helper: Format angka ke format Indonesia
export const formatIndonesianNumber = (value: number): string => {
  return value.toLocaleString('id-ID', {
    minimumFractionDigits: 0,
    maximumFractionDigits: 0
  });
};

// ============================================================================
// CRUD Operations
// ============================================================================

/**
 * Ambil semua transaksi petty cash
 */
export const getPettyCashEntries = async (store: string | null): Promise<PettyCashEntry[]> => {
  const table = getTableName(store);
  try {
    const { data, error } = await supabase
      .from(table)
      .select('*')
      .order('tgl', { ascending: false });

    if (error) {
      console.error('Error fetching petty cash entries:', error);
      return [];
    }

    return (data || []).map(item => ({
      id: String(item.id),
      tgl: item.tgl,
      keterangan: item.keterangan || '',
      type: item.type as 'in' | 'out',
      akun: (item.akun || 'cash') as 'cash' | 'bank',
      saldokeluarmasuk: Number(item.saldokeluarmasuk) || 0,
      saldosaatini: Number(item.saldosaatini) || 0,
    }));
  } catch (err) {
    console.error('getPettyCashEntries error:', err);
    return [];
  }
};

/**
 * Hitung saldo terakhir per akun (cash atau bank)
 */
export const getBalanceByAccount = async (store: string | null, akun: 'cash' | 'bank'): Promise<number> => {
  const table = getTableName(store);
  try {
    const { data, error } = await supabase
      .from(table)
      .select('saldosaatini')
      .eq('akun', akun)
      .order('tgl', { ascending: false })
      .limit(1);

    if (error || !data || data.length === 0) {
      return 0;
    }

    return Number(data[0].saldosaatini) || 0;
  } catch (err) {
    console.error('getBalanceByAccount error:', err);
    return 0;
  }
};

/**
 * Hitung total saldo (cash + bank)
 */
export const getTotalBalance = async (store: string | null): Promise<{ cash: number; bank: number; total: number }> => {
  try {
    const cashBalance = await getBalanceByAccount(store, 'cash');
    const bankBalance = await getBalanceByAccount(store, 'bank');
    
    return {
      cash: cashBalance,
      bank: bankBalance,
      total: cashBalance + bankBalance
    };
  } catch (err) {
    console.error('getTotalBalance error:', err);
    return { cash: 0, bank: 0, total: 0 };
  }
};

/**
 * Tambah transaksi baru - OPTIMIZED for speed
 * ID auto-generated by database (INT8)
 */
export const addPettyCashEntry = async (
  store: string | null,
  entry: {
    tgl: string;
    keterangan: string;
    type: 'in' | 'out';
    akun: 'cash' | 'bank';
    amount: number;
  }
): Promise<{ success: boolean; message: string; data?: PettyCashEntry }> => {
  const table = getTableName(store);
  
  // Konversi tanggal ke timestamp lengkap (dengan waktu saat ini)
  const now = new Date();
  const tglWithTime = `${entry.tgl}T${now.toTimeString().slice(0, 8)}`;
  
  // Ambil saldo terakhir dulu untuk hitung saldo baru
  const currentBalance = await getBalanceByAccount(store, entry.akun);
  
  // Hitung saldo baru
  const saldosaatini = entry.type === 'in' 
    ? currentBalance + entry.amount 
    : currentBalance - entry.amount;
  
  try {
    // INSERT tanpa id - biarkan database auto-generate
    const { data, error } = await supabase
      .from(table)
      .insert([{
        tgl: tglWithTime,
        keterangan: entry.keterangan,
        type: entry.type,
        akun: entry.akun,
        saldokeluarmasuk: entry.amount,
        saldosaatini,
      }])
      .select('id')
      .single();
    
    if (error) {
      console.error('Error adding petty cash entry:', error);
      return { success: false, message: error.message };
    }

    return { 
      success: true, 
      message: 'Transaksi berhasil ditambahkan',
      data: {
        id: String(data.id),
        tgl: tglWithTime,
        keterangan: entry.keterangan,
        type: entry.type,
        akun: entry.akun,
        saldokeluarmasuk: entry.amount,
        saldosaatini,
      }
    };
  } catch (err: any) {
    console.error('addPettyCashEntry error:', err);
    return { success: false, message: err.message || 'Gagal menambah transaksi' };
  }
};

/**
 * Hapus transaksi dan recalculate saldo
 */
export const deletePettyCashEntry = async (
  store: string | null,
  id: string
): Promise<{ success: boolean; message: string }> => {
  const table = getTableName(store);
  try {
    // Ambil info entry yang akan dihapus
    const { data: entryData } = await supabase
      .from(table)
      .select('akun')
      .eq('id', id)
      .single();
    
    const akun = (entryData?.akun || 'cash') as 'cash' | 'bank';
    
    // Hapus entry
    const { error } = await supabase
      .from(table)
      .delete()
      .eq('id', id);

    if (error) {
      console.error('Error deleting petty cash entry:', error);
      return { success: false, message: error.message };
    }

    // Recalculate saldo untuk akun ini
    await recalculateBalancesByAccount(store, akun);

    return { success: true, message: 'Transaksi berhasil dihapus' };
  } catch (err: any) {
    console.error('deletePettyCashEntry error:', err);
    return { success: false, message: err.message || 'Gagal menghapus transaksi' };
  }
};

/**
 * Recalculate saldo untuk satu akun
 */
export const recalculateBalancesByAccount = async (store: string | null, akun: 'cash' | 'bank'): Promise<void> => {
  const table = getTableName(store);
  try {
    const { data, error } = await supabase
      .from(table)
      .select('*')
      .eq('akun', akun)
      .order('tgl', { ascending: true });

    if (error || !data) return;

    let runningBalance = 0;

    for (const entry of data) {
      const amount = Number(entry.saldokeluarmasuk) || 0;
      runningBalance = entry.type === 'in' 
        ? runningBalance + amount 
        : runningBalance - amount;

      if (Number(entry.saldosaatini) !== runningBalance) {
        await supabase
          .from(table)
          .update({ saldosaatini: runningBalance })
          .eq('id', entry.id);
      }
    }
  } catch (err) {
    console.error('recalculateBalancesByAccount error:', err);
  }
};

/**
 * Ambil transaksi dengan filter per akun
 */
export const getEntriesByAccount = async (store: string | null, akun: 'cash' | 'bank'): Promise<PettyCashEntry[]> => {
  const table = getTableName(store);
  try {
    const { data, error } = await supabase
      .from(table)
      .select('*')
      .eq('akun', akun)
      .order('tgl', { ascending: false });

    if (error) {
      console.error('Error fetching entries by account:', error);
      return [];
    }

    return (data || []).map(item => ({
      id: String(item.id),
      tgl: item.tgl,
      keterangan: item.keterangan || '',
      type: item.type as 'in' | 'out',
      akun: item.akun as 'cash' | 'bank',
      saldokeluarmasuk: Number(item.saldokeluarmasuk) || 0,
      saldosaatini: Number(item.saldosaatini) || 0,
    }));
  } catch (err) {
    console.error('getEntriesByAccount error:', err);
    return [];
  }
};
